services:
  elixir:
    build: elixir
    ports:
      - "8080:8080"
    environment:
      DB_URI : ${DB_URI}
      DB_PORT : ${DB_PORT}
      DB_DATABASE : ${DB_DATABASE}
      DB_AUTH : ${DB_AUTH}
      DB_USER : ${DB_USER}
      DB_PASSWORD : ${DB_PASSWORD}
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
    depends_on:
      mongodb:
        condition: service_healthy
volumes:
  data: {}

networks:
  default:
    name: elixir_network